apiVersion: v1
kind: Service
metadata:
  name: back-node-port-service
spec:
  type: NodePort
  selector:
    component: back
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30505
      