name: CI - PREPROD-BACK
on:
  push:
    branches: [dev]

jobs:
  deploy:
    environment: preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build back
        run: |
          npm i
          npm run build
      - name: build back image
        run: docker build -t mo29172/lghorba_back:v${{ github.run_number }} -f docker/back/Dockerfile .
      - name: push back image to docker hub
        run: |
          docker push mo29172/lghorba_back:v${{ github.run_number }}
      - name: update back deployment file version
        run: |
          sed -i -e"s/:latest/:v${{ github.run_number }}/" docker/k8s/back-deployment.yaml


      - name: copy k8s files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'docker/k8s/back-deployment.yaml,docker/k8s/back-node-port-service.yaml,docker/k8s/back-hpa.yaml'
          target: '/srv/k8s/back'
          strip_components: 2

      - name: copy nginx file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'docker/nginx/default.conf'
          target: '/etc/nginx/conf.d'
          strip_components: 2

      - name: apply k8s files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SECOND_USER }}
          password: ${{ secrets.SERVER_SECOND_USER_PASSWORD }}
          script: |
            kubectl delete secret back-envs --ignore-not-found=true
            kubectl create secret generic back-envs \
            --from-literal BACK_PORT=${{ secrets.BACK_PORT }}
            kubectl apply -f /srv/k8s/back
            echo ${{ secrets.SERVER_SECOND_USER_PASSWORD }} | sudo -S systemctl restart nginx